# Generated by Django 2.1.2 on 2018-10-25 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=120, verbose_name='Produto')),
                ('descricao', models.CharField(max_length=280, verbose_name='Descricao')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('endereco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cidade')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Restaurante',
                'verbose_name_plural': 'Restaurantes',
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='restaurante_que_vende',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.Restaurante'),
        ),
    ]
