# Generated by Django 2.1.2 on 2018-10-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('genero', models.CharField(blank=True, choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=2, null=True, verbose_name='Genero')),
                ('endereco', models.CharField(blank=True, max_length=80, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cidade')),
                ('idade', models.CharField(max_length=20, verbose_name='Idade')),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Peso')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('aniversario', models.DateField(blank=True, null=True, verbose_name='Aniversário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
