# Generated by Django 2.1.2 on 2018-12-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20181025_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Declarado')], default='M', max_length=2, verbose_name='Genero'),
            preserve_default=False,
        ),
    ]
